-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 18:58:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shortpaper_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shortpaper_db` ;

-- -----------------------------------------------------
-- Schema shortpaper_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shortpaper_db` DEFAULT CHARACTER SET utf8 ;
USE `shortpaper_db` ;

-- -----------------------------------------------------
-- Table `shortpaper_db`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`admins` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`admins` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NULL,
  `role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`announcement_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`announcement_files` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`announcement_files` (
  `announcement_file_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(100) NOT NULL,
  `file_size` VARCHAR(50) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT current_timestamp,
  `announcement_id` INT NOT NULL,
  PRIMARY KEY (`announcement_file_id`, `announcement_id`),
  INDEX `fk_announcement_files_announcements1_idx` (`announcement_id` ASC) VISIBLE,
  CONSTRAINT `fk_announcement_files_announcements1`
    FOREIGN KEY (`announcement_id`)
    REFERENCES `shortpaper_db`.`announcements` (`announcement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`announcements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`announcements` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`announcements` (
  `announcement_id` INT NOT NULL AUTO_INCREMENT,
  `schedule` VARCHAR(100) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `image_url` VARCHAR(200) NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expired_datetime` DATETIME NULL,
  PRIMARY KEY (`announcement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`comments` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_content` VARCHAR(100) NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`, `file_id`),
  INDEX `fk_comments_files1_idx` (`file_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_files1`
    FOREIGN KEY (`file_id`)
    REFERENCES `shortpaper_db`.`shortpaper_files` (`shortpaper_file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`committees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`committees` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`committees` (
  `committee_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `alternative_email` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `phonenumber` VARCHAR(10) NULL,
  PRIMARY KEY (`committee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpaper_file_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpaper_file_types` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpaper_file_types` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpaper_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpaper_files` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpaper_files` (
  `shortpaper_file_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(100) NOT NULL,
  `file_size` VARCHAR(50) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `explanation_video` VARCHAR(100) NULL,
  `updated_status_datetime` DATETIME NULL,
  `remark` VARCHAR(100) NULL,
  `status` ENUM('approved', 'not_approve', 'not_send') NOT NULL DEFAULT 'not_approve',
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `shortpaper_id` INT NOT NULL,
  `shortpaper_file_type_id` INT NOT NULL,
  PRIMARY KEY (`shortpaper_file_id`, `shortpaper_id`, `shortpaper_file_type_id`),
  INDEX `fk_files_shortpapers1_idx` (`shortpaper_id` ASC) VISIBLE,
  INDEX `fk_files_shortpaper_file_types1_idx` (`shortpaper_file_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_shortpapers1`
    FOREIGN KEY (`shortpaper_id`)
    REFERENCES `shortpaper_db`.`shortpapers` (`shortpaper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_shortpaper_file_types1`
    FOREIGN KEY (`shortpaper_file_type_id`)
    REFERENCES `shortpaper_db`.`shortpaper_file_types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpapers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpapers` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpapers` (
  `shortpaper_id` INT NOT NULL AUTO_INCREMENT,
  `shortpaper_topic` VARCHAR(100) NULL,
  `student_id` VARCHAR(11) NOT NULL,
  `subject_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`shortpaper_id`, `student_id`, `subject_id`),
  INDEX `fk_shortpapers_students1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_shortpapers_subjects1_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_shortpapers_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `shortpaper_db`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shortpapers_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `shortpaper_db`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpapers_has_committees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpapers_has_committees` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpapers_has_committees` (
  `shortpaper_id` INT NOT NULL,
  `committee_id` INT NOT NULL,
  `is_advisor` BIT(1) NOT NULL DEFAULT 0,
  `is_principal` BIT(1) NOT NULL DEFAULT 0,
  `is_committee` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`shortpaper_id`, `committee_id`),
  INDEX `fk_shortpapers_has_committees_committees1_idx` (`committee_id` ASC) VISIBLE,
  INDEX `fk_shortpapers_has_committees_shortpapers_idx` (`shortpaper_id` ASC) VISIBLE,
  CONSTRAINT `fk_shortpapers_has_committees_shortpapers`
    FOREIGN KEY (`shortpaper_id`)
    REFERENCES `shortpaper_db`.`shortpapers` (`shortpaper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shortpapers_has_committees_committees1`
    FOREIGN KEY (`committee_id`)
    REFERENCES `shortpaper_db`.`committees` (`committee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`students` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`students` (
  `student_id` VARCHAR(11) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NULL,
  `alternative_email` VARCHAR(50) NULL,
  `phonenumber` VARCHAR(10) NULL,
  `year` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`subjects` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`subjects` (
  `subject_id` VARCHAR(6) NOT NULL,
  `subject_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`topic_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`topic_categories` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`topic_categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`topic_categories_has_shortpapers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`topic_categories_has_shortpapers` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`topic_categories_has_shortpapers` (
  `category_id` INT NOT NULL,
  `shortpaper_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `shortpaper_id`),
  INDEX `fk_topic_categories_has_shortpapers_shortpapers1_idx` (`shortpaper_id` ASC) VISIBLE,
  INDEX `fk_topic_categories_has_shortpapers_topic_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_categories_has_shortpapers_topic_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shortpaper_db`.`topic_categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_categories_has_shortpapers_shortpapers1`
    FOREIGN KEY (`shortpaper_id`)
    REFERENCES `shortpaper_db`.`shortpapers` (`shortpaper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
