-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 01:06:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shortpaper_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shortpaper_db` ;

-- -----------------------------------------------------
-- Schema shortpaper_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shortpaper_db` DEFAULT CHARACTER SET utf8 ;
USE `shortpaper_db` ;

-- -----------------------------------------------------
-- Table `shortpaper_db`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`admins` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`admins` (
  `admin_id` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NULL,
  `role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`announcement_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`announcement_files` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`announcement_files` (
  `announcement_file_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(100) NOT NULL,
  `file_size` VARCHAR(50) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT current_timestamp,
  `announcement_id` INT NOT NULL,
  PRIMARY KEY (`announcement_file_id`, `announcement_id`),
  INDEX `fk_announcement_files_announcements1_idx` (`announcement_id` ASC) VISIBLE,
  CONSTRAINT `fk_announcement_files_announcements1`
    FOREIGN KEY (`announcement_id`)
    REFERENCES `shortpaper_db`.`announcements` (`announcement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`announcements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`announcements` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`announcements` (
  `announcement_id` INT NOT NULL AUTO_INCREMENT,
  `schedule` VARCHAR(100) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `image_url` VARCHAR(200) NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expired_datetime` DATETIME NULL,
  PRIMARY KEY (`announcement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`article` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`article` (
  `article_id` INT NOT NULL,
  `topic` VARCHAR(100) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `file_name` VARCHAR(100) NOT NULL,
  `file_size` VARCHAR(50) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `year` VARCHAR(6) NOT NULL,
  `subject_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`article_id`, `subject_id`),
  INDEX `fk_article_subjects1_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `shortpaper_db`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`comments` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_content` VARCHAR(100) NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `file_id` INT NOT NULL,
  `reply_commentId` INT NULL,
  `student_id` VARCHAR(11) NOT NULL,
  `committee_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`comment_id`, `file_id`, `student_id`, `committee_id`),
  INDEX `fk_comments_files1_idx` (`file_id` ASC) VISIBLE,
  INDEX `fk_comments_comments1_idx` (`reply_commentId` ASC) VISIBLE,
  INDEX `fk_comments_students1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_comments_committees1_idx` (`committee_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_files1`
    FOREIGN KEY (`file_id`)
    REFERENCES `shortpaper_db`.`shortpaper_files` (`shortpaper_file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`reply_commentId`)
    REFERENCES `shortpaper_db`.`comments` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `shortpaper_db`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_committees1`
    FOREIGN KEY (`committee_id`)
    REFERENCES `shortpaper_db`.`committees` (`committee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`committees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`committees` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`committees` (
  `committee_id` VARCHAR(11) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `alternative_email` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `phonenumber` VARCHAR(10) NULL,
  PRIMARY KEY (`committee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpaper_file_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpaper_file_types` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpaper_file_types` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpaper_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpaper_files` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpaper_files` (
  `shortpaper_file_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(100) NOT NULL,
  `file_size` VARCHAR(50) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `explanation_video` VARCHAR(100) NULL,
  `updated_status_datetime` DATETIME NULL,
  `remark` VARCHAR(100) NULL,
  `status` ENUM('approved', 'not_approve', 'not_send') NOT NULL DEFAULT 'not_approve',
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `shortpaper_id` INT NOT NULL,
  `shortpaper_file_type_id` INT NOT NULL,
  PRIMARY KEY (`shortpaper_file_id`, `shortpaper_id`, `shortpaper_file_type_id`),
  INDEX `fk_files_shortpapers1_idx` (`shortpaper_id` ASC) VISIBLE,
  INDEX `fk_files_shortpaper_file_types1_idx` (`shortpaper_file_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_shortpapers1`
    FOREIGN KEY (`shortpaper_id`)
    REFERENCES `shortpaper_db`.`shortpapers` (`shortpaper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_shortpaper_file_types1`
    FOREIGN KEY (`shortpaper_file_type_id`)
    REFERENCES `shortpaper_db`.`shortpaper_file_types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpapers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpapers` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpapers` (
  `shortpaper_id` INT NOT NULL AUTO_INCREMENT,
  `shortpaper_topic` VARCHAR(100) NULL,
  `student_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`shortpaper_id`, `student_id`),
  INDEX `fk_shortpapers_students1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_shortpapers_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `shortpaper_db`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`shortpapers_has_committees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`shortpapers_has_committees` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`shortpapers_has_committees` (
  `shortpaper_id` INT NOT NULL,
  `committee_id` VARCHAR(11) NOT NULL,
  `is_advisor` BIT(1) NOT NULL DEFAULT 0,
  `is_principal` BIT(1) NOT NULL DEFAULT 0,
  `is_committee` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`shortpaper_id`, `committee_id`),
  INDEX `fk_shortpapers_has_committees_committees1_idx` (`committee_id` ASC) VISIBLE,
  INDEX `fk_shortpapers_has_committees_shortpapers_idx` (`shortpaper_id` ASC) VISIBLE,
  CONSTRAINT `fk_shortpapers_has_committees_shortpapers`
    FOREIGN KEY (`shortpaper_id`)
    REFERENCES `shortpaper_db`.`shortpapers` (`shortpaper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shortpapers_has_committees_committees1`
    FOREIGN KEY (`committee_id`)
    REFERENCES `shortpaper_db`.`committees` (`committee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`students` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`students` (
  `student_id` VARCHAR(11) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NULL,
  `alternative_email` VARCHAR(50) NULL,
  `phonenumber` VARCHAR(10) NULL,
  `status` ENUM('old', 'new') NULL DEFAULT 'new',
  `year` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`students_has_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`students_has_article` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`students_has_article` (
  `student_id` VARCHAR(11) NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `article_id`),
  INDEX `fk_students_has_article_article1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_students_has_article_students1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_article_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `shortpaper_db`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_article_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `shortpaper_db`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`students_has_subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`students_has_subjects` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`students_has_subjects` (
  `student_id` VARCHAR(11) NOT NULL,
  `subject_id` VARCHAR(6) NOT NULL,
  `isRegisteredSubject` BIT(1) NOT NULL DEFAULT 0,
  `isPaperSubject` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`student_id`, `subject_id`),
  INDEX `fk_students_has_subjects_subjects1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_students_has_subjects_students1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_subjects_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `shortpaper_db`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_subjects_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `shortpaper_db`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`subjects` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`subjects` (
  `subject_id` VARCHAR(6) NOT NULL,
  `subject_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`topic_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`topic_categories` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`topic_categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`topic_categories_has_shortpapers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`topic_categories_has_shortpapers` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`topic_categories_has_shortpapers` (
  `category_id` INT NOT NULL,
  `shortpaper_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `shortpaper_id`),
  INDEX `fk_topic_categories_has_shortpapers_shortpapers1_idx` (`shortpaper_id` ASC) VISIBLE,
  INDEX `fk_topic_categories_has_shortpapers_topic_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_categories_has_shortpapers_topic_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shortpaper_db`.`topic_categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_categories_has_shortpapers_shortpapers1`
    FOREIGN KEY (`shortpaper_id`)
    REFERENCES `shortpaper_db`.`shortpapers` (`shortpaper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data All Tables
-- -----------------------------------------------------

-- insert students
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std01', 'John', 'Smith', 'std01@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0123456700', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std02', 'Emily', 'Johnson', 'std02@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0234567890', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std03', 'Michael', 'Davis', 'std03@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0345678900', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std04', 'Sarah', 'Williams', 'std04@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0567890100', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std05', 'David', 'Brown', 'std05@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0678901200', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std06', 'Jessica', 'Martinez', 'std06@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0789012300', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std07', 'Christopher', 'Taylor', 'std07@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0890123400', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std08', 'Samantha', 'Anderson', 'std08@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0901234500', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std09', 'Matthew', 'Wilson', 'std09@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0012345678', '2/2566');
INSERT INTO `shortpaper_db`.`students` (`student_id`, `firstname`, `lastname`, `email`, `password`, `phonenumber`, `year`) VALUES ('std10', 'Olivia', 'Thomas', 'std10@st.sit.kmutt.ac.th', 'RnhpZzA4=', '0938273892', '2/2566');

-- insert admins
INSERT INTO `shortpaper_db`.`admins` (`admin_id`, `email`, `password`, `role`)
VALUES
('stf01', 'staff1@example.com', 'RnhpZzA4=', 'Staff'),
('stf02', 'staff2@example.com', 'RnhpZzA4=', 'Staff'),
('stf03', 'staff3@example.com', 'RnhpZzA4=', 'Staff');

-- insert subjects
INSERT INTO `shortpaper_db`.`subjects` (`subject_id`, `subject_name`) VALUES ('INT421', 'Machine Learning');
INSERT INTO `shortpaper_db`.`subjects` (`subject_id`, `subject_name`) VALUES ('INT101', 'Programming Language');
INSERT INTO `shortpaper_db`.`subjects` (`subject_id`, `subject_name`) VALUES ('INT202', 'Data Structures');
INSERT INTO `shortpaper_db`.`subjects` (`subject_id`, `subject_name`) VALUES ('INT303', 'Database Management Systems');
INSERT INTO `shortpaper_db`.`subjects` (`subject_id`, `subject_name`) VALUES ('INT404', 'Artificial Intelligence');
INSERT INTO `shortpaper_db`.`subjects` (`subject_id`, `subject_name`) VALUES ('INT505', 'Computer Networks');
INSERT INTO `shortpaper_db`.`subjects` (`subject_id`, `subject_name`) VALUES ('INT606', 'Web Development');

-- insert shortpaper file types
INSERT INTO `shortpaper_db`.`shortpaper_file_types` (`type_name`) VALUES ('ใบ บ.1');
INSERT INTO `shortpaper_db`.`shortpaper_file_types` (`type_name`) VALUES ('ส่งครั้งที่ 1');
INSERT INTO `shortpaper_db`.`shortpaper_file_types` (`type_name`) VALUES ('ส่งครั้งที่ 2');
INSERT INTO `shortpaper_db`.`shortpaper_file_types` (`type_name`) VALUES ('รูปเล่มบทความ');
INSERT INTO `shortpaper_db`.`shortpaper_file_types` (`type_name`) VALUES ('ฉบับสมบูรณ์');
INSERT INTO `shortpaper_db`.`shortpaper_file_types` (`type_name`) VALUES ('ใบโอนลิขสิทธิ์');
INSERT INTO `shortpaper_db`.`shortpaper_file_types` (`type_name`) VALUES ('ใบโจรกรรม');

-- insert committees
-- INSERT INTO `shortpaper_db`.`committees` (`committee_id`, `firstname`, `lastname`, `email`, `password`) VALUES ('lec01', 'Unhawa', 'Ninrutsirikun', 'unhawa.nin@mail.kmutt.ac.th', 'RnhpZzA4=');
-- INSERT INTO `shortpaper_db`.`committees` (`committee_id`, `firstname`, `lastname`, `email`, `password`) VALUES ('lec02', 'Olarn', 'Rojanapornpun', 'olarn.roj@mail.kmutt.ac.th', 'RnhpZzA4=');
-- INSERT INTO `shortpaper_db`.`committees` (`committee_id`, `firstname`, `lastname`, `email`, `password`) VALUES ('lec03', 'Umaporn', 'Supasitthimethee', 'uma.sup@mail.kmutt.ac.th', 'RnhpZzA4=');

INSERT INTO `shortpaper_db`.`committees` (`committee_id`, `firstname`, `lastname`, `email`, `password`) VALUES ('lec01', 'Kantapon', 'Tantrapornpong', 'kantapon.tantra@mail.kmutt.ac.th', 'RnhpZzA4=');
INSERT INTO `shortpaper_db`.`committees` (`committee_id`, `firstname`, `lastname`, `email`, `password`) VALUES ('lec02', 'Asamaporn', 'Pladsri', 'asamaporn.jajah@mail.kmutt.ac.th', 'RnhpZzA4=');

-- insert announcements
INSERT INTO `shortpaper_db`.`announcements` (`announcement_id`, `schedule`, `content`) VALUES ('1', '1-6 สิงหาคม 2567', 'อัปโหลดแบบ บ.1 ผ่านการลงนามของอาจารย์ที่ปรึกษา ผ่านทาง
http://www2.sit.kmutt.ac.th/isreport/New/');
INSERT INTO `shortpaper_db`.`announcements` (`announcement_id`, `schedule`, `content`) VALUES ('2', '10 กันยายน 2567', 'ส่งงานครั้งที่ 1 (ตามข้อกำหนดของอาจารย์ที่ปรึกษา)');
INSERT INTO `shortpaper_db`.`announcements` (`announcement_id`, `schedule`, `content`) VALUES ('3', '1 ตุลาคม 2567', 'ส่งงานครั้งที่ 2t (ตามข้อกำหนดของอาจารย์ที่ปรึกษา)');
INSERT INTO `shortpaper_db`.`announcements` (`announcement_id`, `schedule`, `content`) VALUES ('4', '15 ตุลาคม 2567', 'ส่ง Short Paper ครั้งที่ 1 ในรูปแบบของบทความ 3 ชุด (ไม่ต้องเข้าเล่ม)
ณ ห้องสมุดคณะเทคโนโลยีสารสนเทศ');
INSERT INTO `shortpaper_db`.`announcements` (`announcement_id`, `schedule`, `content`) VALUES ('5', '29 ตุลาคม 2567', 'รับบทความคืนครั้งที่ 1');