-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 22:55:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shortpaper_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shortpaper_db` ;

-- -----------------------------------------------------
-- Schema shortpaper_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shortpaper_db` DEFAULT CHARACTER SET utf8 ;
USE `shortpaper_db` ;

-- -----------------------------------------------------
-- Table `shortpaper_db`.`file_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`file_status` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`file_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `b_one` BIT(1) NULL,
  `paper_one` BIT(1) NULL,
  `paper_two` BIT(1) NULL,
  `article` BIT(1) NULL,
  `plagiarism` BIT(1) NULL,
  `copyright` BIT(1) NULL,
  `robbery` BIT(1) NULL,
  `final` BIT(1) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`subjects` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` VARCHAR(6) NOT NULL,
  `subject_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`users` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` VARCHAR(11) NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `role` VARCHAR(10) NULL DEFAULT 'student',
  `email` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(10) NULL,
  `year` VARCHAR(4) NULL,
  `registered_subjectid` INT NULL,
  `shortpaper_subjectid` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_subjects1_idx` (`registered_subjectid` ASC) VISIBLE,
  INDEX `fk_users_subjects2_idx` (`shortpaper_subjectid` ASC) VISIBLE,
  CONSTRAINT `fk_users_subjects1`
    FOREIGN KEY (`registered_subjectid`)
    REFERENCES `shortpaper_db`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_subjects2`
    FOREIGN KEY (`shortpaper_subjectid`)
    REFERENCES `shortpaper_db`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(200) NOT NULL,
  `committee_first` INT NULL,
  `committee_second` INT NULL,
  `committee_third` INT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_project_users1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_users1`
    FOREIGN KEY (`student_id`)
    REFERENCES `shortpaper_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`files` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(100) NOT NULL,
  `filesize` VARCHAR(50) NOT NULL,
  `explanation_video` VARCHAR(200) NULL,
  `data` LONGBLOB NULL,
  `filetype` VARCHAR(50) NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_file_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_files_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_file_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `shortpaper_db`.`file_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `shortpaper_db`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`comments` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comments` LONGTEXT NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '\n',
  `updated_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reply_commentid` INT NULL,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_comments1_idx` (`reply_commentid` ASC) VISIBLE,
  INDEX `fk_comments_files1_idx` (`file_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`reply_commentid`)
    REFERENCES `shortpaper_db`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_files1`
    FOREIGN KEY (`file_id`)
    REFERENCES `shortpaper_db`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortpaper_db`.`announcements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shortpaper_db`.`announcements` ;

CREATE TABLE IF NOT EXISTS `shortpaper_db`.`announcements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('published', 'draft', 'archived') NOT NULL DEFAULT 'draft',
  `image_url` LONGTEXT NULL,
  `author_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_announcements_users1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_announcements_files1_idx` (`file_id` ASC) VISIBLE,
  CONSTRAINT `fk_announcements_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `shortpaper_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announcements_files1`
    FOREIGN KEY (`file_id`)
    REFERENCES `shortpaper_db`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
